stages:
  - test
  - deploy

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null
git
services:
- postgres


# We test PHP5.6
test:5.6:
  stage: test
  image: php:5.6
  script:
  - phpunit Tests/postTests

# We test PHP7.0
test:7.0:
  stage: test
  image: php:7.0
  script:
  - phpunit Tests/postTests

deployment:
  stage: deploy
  script:
  - pwd
  - scp -o StrictHostKeyChecking=no -r /home/gitlab-runner/builds/b95d5946/0/hr1316/WebAppsServer cl5616@shell4.doc.ic.ac.uk:/vol/project/2017/271/g1727111
  only:
  - master
