before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d ’\r’ | ssh-add - > /dev/null

services:
- postgres


# We test PHP5.6
test:5.6:
  image: php:5.6
  script:
  - phpunit Tests/postTests

# We test PHP7.0
test:7.0:
  image: php:7.0
  script:
  - phpunit Tests/postTests
